# Generated by Django 4.2.1 on 2023-05-28 06:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TasksRoom',
            fields=[
                ('id_room', models.UUIDField(default=uuid.UUID('f135b4e2-c364-4c28-9633-fedad0235169'), editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField()),
                ('description', models.TextField(blank=True, max_length=500)),
                ('users', models.ManyToManyField(related_name='rooms', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField()),
                ('description', models.TextField(blank=True, max_length=500)),
                ('importance', models.CharField(blank=True, choices=[('HIG', 'High'), ('MED', 'Medium'), ('LOW', 'Low')], default='')),
                ('current_state', models.CharField(blank=True, choices=[('PEND', 'Pending'), ('RUNN', 'In Progress'), ('COMP', 'Completed')], default='PEND')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.tasksroom')),
            ],
        ),
    ]
