# Generated by Django 4.2.1 on 2023-06-08 02:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='current_state',
            field=models.CharField(blank=True, choices=[('TODO', 'TO-DO'), ('INPROG', 'In Progress'), ('DONE', 'Done')], default='TODO', max_length=10),
        ),
        migrations.AlterField(
            model_name='task',
            name='importance',
            field=models.CharField(blank=True, choices=[('HIG', 'High'), ('MED', 'Medium'), ('LOW', 'Low')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='tasksroom',
            name='id_room',
            field=models.UUIDField(default=uuid.UUID('e7449b70-2274-4bef-9c39-0c414a5274bd'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tasksroom',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
